# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for more information:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates
# https://containers.dev/guide/dependabot

version: 2
updates:
 - package-ecosystem: "devcontainers"
   directory: "/"
   schedule:
     interval: weekly

 - package-ecosystem: "npm"
   directory: "/"
   schedule:
     interval: daily
   open-pull-requests: true
   versioning-strategy: "bump-minor"
 
 - package-ecosystem: "daily"
   directory: "/"
   schedule:
     interval: daily
   open-pull-requests: true
   security-severity: "critical"

workflows:
  main:
    name: "Main Workflow"
    on:
      - pull_request
    jobs:
      - job1:
          runs-on: ubuntu-lastest
          step:
            - name: "Update dependencies"
              uses: actions/dependabot/pull-request-review@v2
