# This is a basic workflow to help you get started with Actions

name: CI/CD Workflow

on:    
  - push
  - pull_request 

jobs:  
  build:    
    runs-on: ubuntu-latest    
    steps:      
      - uses: actions/checkout@v2
      
      - name: Install dependencies
        run: npm install
      
      - name: Run tests
        run: npm start
        
      - name: Build Docker image
        run: docker build -t my-mongo .
  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: ${{github.event_name == 'push'}}
    environment: production
    steps:
      - uses: actions/checkout@v2

      - name: Deploy to Guthub Pages
        uses: JamesIves/github-pages-deploy-action@4.3.1
        with:
          branch: gh-pages
          folder: ./build      
