# This is a basic workflow to help you get started with Actions

name: CI/CD Workflow
permissions:
  id-token: write
  contents: read
on:    
  - push
  - pull_request 
  
env:
  # ACTIONS_ID_TOKEN_REQUEST_URL: https://api.github.com/actions/id-token-request
  GITHUB_TOKEN: ${{ secrets.TOKEN_CODE }}
  
jobs:  
  build:    
    runs-on: ubuntu-latest    
    steps:      
      - uses: actions/checkout@v3
      
      - name: Install dependencies
        run: npm install
        
      - name: Build application
        run: |
          mkdir -p ./dist
          cd dist
          npm run build

      - name: Create .env file
        run: |
          mkdir -p ./config
          echo MONGODB_URL=${{ secrets.DEV_DATABASE_URL }} >> ./config/.env
          echo DBNAME=${{ secrets.DBNAME }} >> ./config/.env
          
      - uses: actions/upload-artifact@v2
        with:
          name: my-app
          path: ./dist
      # - name: Run tests
      #   run: npm test
        
      # - name: Build Docker image
      #   run: docker build -t my-mongo .
  deploy:
    needs: build
    runs-on: ubuntu-latest    
    if: ${{github.event_name == 'push'}}
    environment: github-pages
    steps:
      - uses: actions/checkout@v3
      
      - name: Create gh-pages branch if not exists
        run: |
          git fetch --all
          if ! git branch -r | grep -q "origin/gh-pages"; then
            git checkout -b gh-pages
          else
            git checkout gh-pages
            git reset --hard origin/gh-pages
          fi
          
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: my-app         
          
      - name: Deploy to Guthub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{secrets.TOKEN_CODE}}
          branch: gh-pages
          folder: ./dist      
