# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Nest.js CI

# env:
#   REGISTRY: ghcr.io
#   DOCKER_IMAGE: ${{github.repository}}  

on:
  push:
    branches: [ "main" ]  

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v3
      - name: Setup node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18.17.1
          cache: 'npm'
      - name: Create .env file
            run:|
              echo MONGODB_URL=${{ secrets.DEV_DATABASE_URL }} >> .env
              echo DBNAME=${{ secrets.DBNAME }} >> .env
      - run: npm install
      - run: npm run test:e2e
      
  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Source Code
    - uses: actions/checkout@v3
    - name: Set up docker build
      id: buildx
      uses: docker/setup-buildx-action@v2
    - name: Login to ghcr
      uses: docker/login-action@v2      
      with:
        username: ${{secrets.DOCKER_USER}}
        password: ${{secrets.DOCKER_PWD}}
        
    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: ${{ secrets.DOCKER_USER }}/${{ secrets.DOCKER_IMAGE_NAME }}:latest
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test
